/*
 * *© Copyright 2018 - 2020 Visa. All Rights Reserved.**
 *
 * NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.*
 *
 *  By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy (developer.visa.com/privacy).In addition, all permissible uses of the Software must be in support of Visa products, programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com). **THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL FAULTS” BASIS WITHOUT WARRANTY OR  CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.** All brand names are the property of their respective owners, used for identification purposes only, and do not imply product endorsement or affiliation with Visa. Any links to third party sites are for your information only and equally  do not constitute a Visa endorsement. Visa has no insight into and control over third party content and code and disclaims all liability for any such components, including continued availability and functionality. Benefits depend on implementation details and business factors and coding steps shown are exemplary only and do not reflect all necessary elements for the described capabilities. Capabilities and features are subject to Visa’s terms and conditions and may require development,implementation and resources by you based on your business and operational details. Please refer to the specific API documentation for details on the requirements, eligibility and geographic availability.*
 *
 * This Software includes programs, concepts and details under continuing development by Visa. Any Visa features,functionality, implementation, branding, and schedules may be amended, updated or canceled at Visa’s discretion.The timing of widespread availability of programs and functionality is also subject to a number of factors outside Visa’s control,including but not limited to deployment of necessary infrastructure by issuers, acquirers, merchants and mobile device manufacturers.*
 *
 */

/*
 * Funds Transfer API
 * The Funds Transfer API can pull funds from the sender&apos;s Visa account (in preparation for pushing funds to a recipient&apos;s account) in an Account Funding Transaction (AFT).  Additionally, the Funds Transfer API also provides functionality to push funds to the recipient&apos;s Visa account in an Original Credit Transaction (OCT).  If a transaction is declined, the Funds Transfer API can also return the funds to the sender&apos;s funding source in an Account Funding Transaction Reversal (AFTR). The API has been enhanced to allow originators to send their PushFundsTransactions(OCTs) and PullFundsTransactions(AFTs) to Visa for routing to multiple U.S. debit networks.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.funds_transfer_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Request body for creating in push funds transfer
 */
@ApiModel(description = "Request body for creating in push funds transfer")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2019-03-27T10:55:08.119+05:30[Asia/Kolkata]")
public class PushfundspostPayload {


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("businessApplicationId")
    private String businessApplicationId = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("retrievalReferenceNumber")
    private String retrievalReferenceNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("cardAcceptor")
    private CardAcceptor cardAcceptor = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("messageReasonCode")
    private Integer messageReasonCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderAddress")
    private String senderAddress = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderCity")
    private String senderCity = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("sourceOfFundsCode")
    private String sourceOfFundsCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("recipientName")
    private String recipientName = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderMiddleInitial")
    private String senderMiddleInitial = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderName")
    private String senderName = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("recipientState")
    private String recipientState = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("surcharge")
    private String surcharge = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderStateCode")
    private String senderStateCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("merchantCategoryCode")
    private Integer merchantCategoryCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderLastName")
    private String senderLastName = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("pointOfServiceData")
    private PointOfServiceData pointOfServiceData = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("sharingGroupCode")
    private String sharingGroupCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("acquirerCountryCode")
    private Integer acquirerCountryCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderReference")
    private String senderReference = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("recipientPrimaryAccountNumber")
    private String recipientPrimaryAccountNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("recipientLastName")
    private String recipientLastName = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("nationalReimbursementFee")
    private Double nationalReimbursementFee = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderPostalCode")
    private String senderPostalCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderFirstName")
    private String senderFirstName = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderAccountNumber")
    private String senderAccountNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("feeProgramIndicator")
    private String feeProgramIndicator = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderIdentificationNumberBusiness")
    private String senderIdentificationNumberBusiness = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("transactionCurrencyCode")
    private String transactionCurrencyCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("acquiringBin")
    private Integer acquiringBin = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("accountType")
    private String accountType = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("merchantPseudoAbaNumber")
    private String merchantPseudoAbaNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("transactionIdentifier")
    private Long transactionIdentifier = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("localTransactionDateTime")
    private String localTransactionDateTime = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("recipientFirstName")
    private String recipientFirstName = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("amount")
    private Double amount = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderDateOfBirth")
    private String senderDateOfBirth = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("recipientMiddleInitial")
    private String recipientMiddleInitial = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("recipientCardExpiryDate")
    private String recipientCardExpiryDate = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("recipientCountryCode")
    private String recipientCountryCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderIdentificationNumberIndividual")
    private String senderIdentificationNumberIndividual = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("systemsTraceAuditNumber")
    private Integer systemsTraceAuditNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderCountryCode")
    private String senderCountryCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("merchantVerificationValue")
    private MerchantVerificationValue merchantVerificationValue = null;

    public PushfundspostPayload businessApplicationId(String businessApplicationId) {
        this.businessApplicationId = businessApplicationId;
        return this;
    }


    /**
     * Identifies the programs&#x27; business application type for VisaNet transaction processing&lt;br&gt;&lt;br&gt;For Money Transfer, AA applies to transactions where the sender and recipient are the same person and PP applies to transactions where the sender and recipient are not the same person.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#business_application_identifier\&quot;&gt;businessApplicationId&lt;/a&gt; codes
     *
     * @return businessApplicationId
     **/
    @ApiModelProperty(value = "Identifies the programs' business application type for VisaNet transaction processing<br><br>For Money Transfer, AA applies to transactions where the sender and recipient are the same person and PP applies to transactions where the sender and recipient are not the same person.<br><br>Refer to <a href=\"/request_response_codes#business_application_identifier\">businessApplicationId</a> codes")
    public String getBusinessApplicationId() {
        return businessApplicationId;
    }

    public void setBusinessApplicationId(String businessApplicationId) {
        this.businessApplicationId = businessApplicationId;
    }

    public PushfundspostPayload retrievalReferenceNumber(String retrievalReferenceNumber) {
        this.retrievalReferenceNumber = retrievalReferenceNumber;
        return this;
    }


    /**
     * A value used to tie together service calls related to a single financial transaction. When passing Account Funding Transaction (AFT) and an Original Credit Transaction (OCT) methods, this value must differ between the two methods. When passing the Account Funding Transaction Reversal (AFTR) method, this value must match the retrievalReferenceNumber previously passed with the AFT method for this transaction.&lt;br&gt;&lt;br&gt; Recommended Format : ydddhhnnnnnn&lt;br&gt;&lt;br&gt;The first fours digits must be a valid yddd date in the Julian date format, where the first digit &#x3D; 0-9 (last digit of current year) and the next three digits &#x3D; 001-366 (number of the day in the year). hh can be the two digit hour in a 24 hour clock (00-23) during which the transaction is performed.&lt;br&gt;&lt;br&gt; nnnnnn can be the systemsTraceAuditNumber or any 6 digit number.
     *
     * @return retrievalReferenceNumber
     **/
    @ApiModelProperty(required = true, value = "A value used to tie together service calls related to a single financial transaction. When passing Account Funding Transaction (AFT) and an Original Credit Transaction (OCT) methods, this value must differ between the two methods. When passing the Account Funding Transaction Reversal (AFTR) method, this value must match the retrievalReferenceNumber previously passed with the AFT method for this transaction.<br><br> Recommended Format : ydddhhnnnnnn<br><br>The first fours digits must be a valid yddd date in the Julian date format, where the first digit = 0-9 (last digit of current year) and the next three digits = 001-366 (number of the day in the year). hh can be the two digit hour in a 24 hour clock (00-23) during which the transaction is performed.<br><br> nnnnnn can be the systemsTraceAuditNumber or any 6 digit number.")
    public String getRetrievalReferenceNumber() {
        return retrievalReferenceNumber;
    }

    public void setRetrievalReferenceNumber(String retrievalReferenceNumber) {
        this.retrievalReferenceNumber = retrievalReferenceNumber;
    }

    public PushfundspostPayload cardAcceptor(CardAcceptor cardAcceptor) {
        this.cardAcceptor = cardAcceptor;
        return this;
    }


    /**
     * Get cardAcceptor
     *
     * @return cardAcceptor
     **/
    @ApiModelProperty(required = true, value = "")
    public CardAcceptor getCardAcceptor() {
        return cardAcceptor;
    }

    public void setCardAcceptor(CardAcceptor cardAcceptor) {
        this.cardAcceptor = cardAcceptor;
    }

    public PushfundspostPayload messageReasonCode(Integer messageReasonCode) {
        this.messageReasonCode = messageReasonCode;
        return this;
    }


    /**
     * Contains codes that combined with some other fields such as the BAI (Business Application Id) identify some unique use cases. For Sales Tax rebates this field should be populated with the value 5120 (Value-added tax/Sales Tax) along with the businessApplicationId field set to the value &#x27;FD&#x27; which indicates this push funds transfer is being conducted in order to facilitate a sales tax refund.
     *
     * @return messageReasonCode
     **/
    @ApiModelProperty(value = "Contains codes that combined with some other fields such as the BAI (Business Application Id) identify some unique use cases. For Sales Tax rebates this field should be populated with the value 5120 (Value-added tax/Sales Tax) along with the businessApplicationId field set to the value 'FD' which indicates this push funds transfer is being conducted in order to facilitate a sales tax refund.")
    public Integer getMessageReasonCode() {
        return messageReasonCode;
    }

    public void setMessageReasonCode(Integer messageReasonCode) {
        this.messageReasonCode = messageReasonCode;
    }

    public PushfundspostPayload senderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
        return this;
    }


    /**
     * If the transaction is a money transfer and cross-border or U.S. domestic, this field must contain the sender&#x27;s address.&lt;br&gt;&lt;br&gt;If the transaction is a funds disbursement and cross-border or U.S. domestic, this field must contain either the address of the merchant or government entity sending the funds disbursement.&lt;br&gt;&lt;br&gt;If the transaction is a pre-paid load or credit card bill pay and U.S. domestic, this field must contain the sender&#x27;s address.
     *
     * @return senderAddress
     **/
    @ApiModelProperty(value = "If the transaction is a money transfer and cross-border or U.S. domestic, this field must contain the sender's address.<br><br>If the transaction is a funds disbursement and cross-border or U.S. domestic, this field must contain either the address of the merchant or government entity sending the funds disbursement.<br><br>If the transaction is a pre-paid load or credit card bill pay and U.S. domestic, this field must contain the sender's address.")
    public String getSenderAddress() {
        return senderAddress;
    }

    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }

    public PushfundspostPayload senderCity(String senderCity) {
        this.senderCity = senderCity;
        return this;
    }


    /**
     * If the transaction is a money transfer and cross-border or U.S. domestic, this field must contain the sender&#x27;s city.&lt;br&gt;&lt;br&gt;If the transaction is a funds disbursement and cross-border or U.S. domestic, this field must contain either the city of the merchant or government entity sending the funds disbursement.&lt;br&gt;&lt;br&gt;If the transaction is a pre-paid load or credit card bill pay and U.S. domestic, this field must contain the sender&#x27;s city.
     *
     * @return senderCity
     **/
    @ApiModelProperty(value = "If the transaction is a money transfer and cross-border or U.S. domestic, this field must contain the sender's city.<br><br>If the transaction is a funds disbursement and cross-border or U.S. domestic, this field must contain either the city of the merchant or government entity sending the funds disbursement.<br><br>If the transaction is a pre-paid load or credit card bill pay and U.S. domestic, this field must contain the sender's city.")
    public String getSenderCity() {
        return senderCity;
    }

    public void setSenderCity(String senderCity) {
        this.senderCity = senderCity;
    }

    public PushfundspostPayload sourceOfFundsCode(String sourceOfFundsCode) {
        this.sourceOfFundsCode = sourceOfFundsCode;
        return this;
    }


    /**
     * If the transaction is a money transfer, the field is required and must contain a valid &lt;a href&#x3D;\&quot;/request_response_codes#source_of_funds\&quot;&gt;sourceOfFundsCode&lt;/a&gt; code that matches the funding instrument.&lt;br&gt;&lt;br&gt;If the transaction is a funds disbursement, the field is required and most likely contains a \&quot;05\&quot; as the &lt;a href&#x3D;\&quot;/request_response_codes#source_of_funds\&quot;&gt;sourceOfFundsCode&lt;/a&gt; code to identify that the merchant or government entity used a deposit account to fund the disbursement&lt;br&gt;&lt;br&gt;If the transaction is a pre-paid load, the field is required if the transaction is non-U.S. domestic.&lt;br&gt;&lt;br&gt;If the transaction is a credit bill pay, the field is required if the transaction is non-U.S. domestic, and the &lt;a href&#x3D;\&quot;/request_response_codes#source_of_funds\&quot;&gt;sourceOfFundsCode&lt;/a&gt; code must not contain a \&quot;01\&quot; or \&quot;06\&quot;.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#source_of_funds\&quot;&gt;sourceOfFundsCode&lt;/a&gt; codes
     *
     * @return sourceOfFundsCode
     **/
    @ApiModelProperty(value = "If the transaction is a money transfer, the field is required and must contain a valid <a href=\"/request_response_codes#source_of_funds\">sourceOfFundsCode</a> code that matches the funding instrument.<br><br>If the transaction is a funds disbursement, the field is required and most likely contains a \"05\" as the <a href=\"/request_response_codes#source_of_funds\">sourceOfFundsCode</a> code to identify that the merchant or government entity used a deposit account to fund the disbursement<br><br>If the transaction is a pre-paid load, the field is required if the transaction is non-U.S. domestic.<br><br>If the transaction is a credit bill pay, the field is required if the transaction is non-U.S. domestic, and the <a href=\"/request_response_codes#source_of_funds\">sourceOfFundsCode</a> code must not contain a \"01\" or \"06\".<br><br>Refer to <a href=\"/request_response_codes#source_of_funds\">sourceOfFundsCode</a> codes")
    public String getSourceOfFundsCode() {
        return sourceOfFundsCode;
    }

    public void setSourceOfFundsCode(String sourceOfFundsCode) {
        this.sourceOfFundsCode = sourceOfFundsCode;
    }

    public PushfundspostPayload recipientName(String recipientName) {
        this.recipientName = recipientName;
        return this;
    }


    /**
     * Recipient name is required for cross-border enhanced money transfer OCTs.
     *
     * @return recipientName
     **/
    @ApiModelProperty(value = "Recipient name is required for cross-border enhanced money transfer OCTs.")
    public String getRecipientName() {
        return recipientName;
    }

    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName;
    }

    public PushfundspostPayload senderMiddleInitial(String senderMiddleInitial) {
        this.senderMiddleInitial = senderMiddleInitial;
        return this;
    }


    /**
     * This field contains sender&#x27;s middle initial
     *
     * @return senderMiddleInitial
     **/
    @ApiModelProperty(value = "This field contains sender's middle initial")
    public String getSenderMiddleInitial() {
        return senderMiddleInitial;
    }

    public void setSenderMiddleInitial(String senderMiddleInitial) {
        this.senderMiddleInitial = senderMiddleInitial;
    }

    public PushfundspostPayload senderName(String senderName) {
        this.senderName = senderName;
        return this;
    }


    /**
     * If the transaction is a money transfer and cross-border or U.S. domestic, this field must contain the sender&#x27;s name.&lt;br&gt;&lt;br&gt;If the transaction is a funds disbursement and cross-border or U.S. domestic, this field must contain either the name of the merchant or government entity sending the funds disbursement.&lt;br&gt;&lt;br&gt;If the transaction is a pre-paid load or credit card bill pay and U.S. domestic, this field must contain the sender&#x27;s name.&lt;br&gt;&lt;br&gt;Recommended Format: Last Name/Family Surname 1 + Space + Last Name/Family Surname 2 (optional) + Space + First Name/Given Name + Space + Middle Initial or Middle name (optional) + space&lt;br&gt;&lt;br&gt;Example: Doe John A
     *
     * @return senderName
     **/
    @ApiModelProperty(value = "If the transaction is a money transfer and cross-border or U.S. domestic, this field must contain the sender's name.<br><br>If the transaction is a funds disbursement and cross-border or U.S. domestic, this field must contain either the name of the merchant or government entity sending the funds disbursement.<br><br>If the transaction is a pre-paid load or credit card bill pay and U.S. domestic, this field must contain the sender's name.<br><br>Recommended Format: Last Name/Family Surname 1 + Space + Last Name/Family Surname 2 (optional) + Space + First Name/Given Name + Space + Middle Initial or Middle name (optional) + space<br><br>Example: Doe John A")
    public String getSenderName() {
        return senderName;
    }

    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    public PushfundspostPayload recipientState(String recipientState) {
        this.recipientState = recipientState;
        return this;
    }


    /**
     * Required if RecipientCountryCode is either 124(CAN) or 840(USA)
     *
     * @return recipientState
     **/
    @ApiModelProperty(value = "Required if RecipientCountryCode is either 124(CAN) or 840(USA) ")
    public String getRecipientState() {
        return recipientState;
    }

    public void setRecipientState(String recipientState) {
        this.recipientState = recipientState;
    }

    public PushfundspostPayload surcharge(String surcharge) {
        this.surcharge = surcharge;
        return this;
    }


    /**
     * When present, this field contains the sender&#x27;s surcharge as assessed by the originator. Values in this field must be in the same currency and format as defined in the amount field.&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt;&lt;br&gt;Supported only in the US.
     *
     * @return surcharge
     **/
    @ApiModelProperty(value = "When present, this field contains the sender's surcharge as assessed by the originator. Values in this field must be in the same currency and format as defined in the amount field.<br><br><b>Note:</b><br>Supported only in the US.")
    public String getSurcharge() {
        return surcharge;
    }

    public void setSurcharge(String surcharge) {
        this.surcharge = surcharge;
    }

    public PushfundspostPayload senderStateCode(String senderStateCode) {
        this.senderStateCode = senderStateCode;
        return this;
    }


    /**
     * Required if senderCountryCode is either 124(CAN) or 840(USA)
     *
     * @return senderStateCode
     **/
    @ApiModelProperty(value = "Required if senderCountryCode is either 124(CAN) or 840(USA)")
    public String getSenderStateCode() {
        return senderStateCode;
    }

    public void setSenderStateCode(String senderStateCode) {
        this.senderStateCode = senderStateCode;
    }

    public PushfundspostPayload merchantCategoryCode(Integer merchantCategoryCode) {
        this.merchantCategoryCode = merchantCategoryCode;
        return this;
    }


    /**
     * If provided, then the value overrides the one present in onboarding data. If the merchantCategoryCode value is not populated in onboarding data then this field is mandatory.&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt; required if not provided during onboarding
     *
     * @return merchantCategoryCode
     **/
    @ApiModelProperty(value = "If provided, then the value overrides the one present in onboarding data. If the merchantCategoryCode value is not populated in onboarding data then this field is mandatory.<br><br><b>Note:</b> required if not provided during onboarding")
    public Integer getMerchantCategoryCode() {
        return merchantCategoryCode;
    }

    public void setMerchantCategoryCode(Integer merchantCategoryCode) {
        this.merchantCategoryCode = merchantCategoryCode;
    }

    public PushfundspostPayload senderLastName(String senderLastName) {
        this.senderLastName = senderLastName;
        return this;
    }


    /**
     * This field contains sender&#x27;s last name
     *
     * @return senderLastName
     **/
    @ApiModelProperty(value = "This field contains sender's last name")
    public String getSenderLastName() {
        return senderLastName;
    }

    public void setSenderLastName(String senderLastName) {
        this.senderLastName = senderLastName;
    }

    public PushfundspostPayload pointOfServiceData(PointOfServiceData pointOfServiceData) {
        this.pointOfServiceData = pointOfServiceData;
        return this;
    }


    /**
     * Get pointOfServiceData
     *
     * @return pointOfServiceData
     **/
    @ApiModelProperty(value = "")
    public PointOfServiceData getPointOfServiceData() {
        return pointOfServiceData;
    }

    public void setPointOfServiceData(PointOfServiceData pointOfServiceData) {
        this.pointOfServiceData = pointOfServiceData;
    }

    public PushfundspostPayload sharingGroupCode(String sharingGroupCode) {
        this.sharingGroupCode = sharingGroupCode;
        return this;
    }


    /**
     * This field is optionally used by Push Payments Gateway participants (merchants and acquirers) to specify the network access priority.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#network_id_and_sharing_group_code\&quot;&gt;Sharing Group Code&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt;&lt;br&gt;Supported only in US for domestic transactions involving Push Payments Gateway Service.
     *
     * @return sharingGroupCode
     **/
    @ApiModelProperty(value = "This field is optionally used by Push Payments Gateway participants (merchants and acquirers) to specify the network access priority.<br><br>Refer to <a href=\"/request_response_codes#network_id_and_sharing_group_code\">Sharing Group Code</a><br><br><b>Note:</b><br>Supported only in US for domestic transactions involving Push Payments Gateway Service.")
    public String getSharingGroupCode() {
        return sharingGroupCode;
    }

    public void setSharingGroupCode(String sharingGroupCode) {
        this.sharingGroupCode = sharingGroupCode;
    }

    public PushfundspostPayload acquirerCountryCode(Integer acquirerCountryCode) {
        this.acquirerCountryCode = acquirerCountryCode;
        return this;
    }


    /**
     * Use a 3-digit numeric country code for the country of the BIN under which your Visa Direct solution is registered. This must match the information provided during program enrollment.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#iso_country_and_currency_codes\&quot;&gt;ISO Codes&lt;/a&gt;
     *
     * @return acquirerCountryCode
     **/
    @ApiModelProperty(required = true, value = "Use a 3-digit numeric country code for the country of the BIN under which your Visa Direct solution is registered. This must match the information provided during program enrollment.<br><br>Refer to <a href=\"/request_response_codes#iso_country_and_currency_codes\">ISO Codes</a>")
    public Integer getAcquirerCountryCode() {
        return acquirerCountryCode;
    }

    public void setAcquirerCountryCode(Integer acquirerCountryCode) {
        this.acquirerCountryCode = acquirerCountryCode;
    }

    public PushfundspostPayload senderReference(String senderReference) {
        this.senderReference = senderReference;
        return this;
    }


    /**
     * If the transaction is a money transfer, pre-paid load, or credit card bill pay, and if the sender intends to fund the transaction with a non-financial instrument (for example, cash), a reference number unique to the sender is required.&lt;br&gt;&lt;br&gt;If the transaction is a funds disbursement, the field is required.&lt;br&gt;&lt;br&gt; This field is required if senderAccountNumber is not sent.
     *
     * @return senderReference
     **/
    @ApiModelProperty(value = "If the transaction is a money transfer, pre-paid load, or credit card bill pay, and if the sender intends to fund the transaction with a non-financial instrument (for example, cash), a reference number unique to the sender is required.<br><br>If the transaction is a funds disbursement, the field is required.<br><br> This field is required if senderAccountNumber is not sent.")
    public String getSenderReference() {
        return senderReference;
    }

    public void setSenderReference(String senderReference) {
        this.senderReference = senderReference;
    }

    public PushfundspostPayload recipientPrimaryAccountNumber(String recipientPrimaryAccountNumber) {
        this.recipientPrimaryAccountNumber = recipientPrimaryAccountNumber;
        return this;
    }


    /**
     * The recipient&#x27;s PAN.
     *
     * @return recipientPrimaryAccountNumber
     **/
    @ApiModelProperty(required = true, value = "The recipient's PAN.")
    public String getRecipientPrimaryAccountNumber() {
        return recipientPrimaryAccountNumber;
    }

    public void setRecipientPrimaryAccountNumber(String recipientPrimaryAccountNumber) {
        this.recipientPrimaryAccountNumber = recipientPrimaryAccountNumber;
    }

    public PushfundspostPayload recipientLastName(String recipientLastName) {
        this.recipientLastName = recipientLastName;
        return this;
    }


    /**
     * When present, this field contains recipient&#x27;s last name
     *
     * @return recipientLastName
     **/
    @ApiModelProperty(value = "When present, this field contains recipient's last name")
    public String getRecipientLastName() {
        return recipientLastName;
    }

    public void setRecipientLastName(String recipientLastName) {
        this.recipientLastName = recipientLastName;
    }

    public PushfundspostPayload nationalReimbursementFee(Double nationalReimbursementFee) {
        this.nationalReimbursementFee = nationalReimbursementFee;
        return this;
    }


    /**
     * When present, this field contains the IRF fees.
     *
     * @return nationalReimbursementFee
     **/
    @ApiModelProperty(value = "When present, this field contains the IRF fees.")
    public Double getNationalReimbursementFee() {
        return nationalReimbursementFee;
    }

    public void setNationalReimbursementFee(Double nationalReimbursementFee) {
        this.nationalReimbursementFee = nationalReimbursementFee;
    }

    public PushfundspostPayload senderPostalCode(String senderPostalCode) {
        this.senderPostalCode = senderPostalCode;
        return this;
    }


    /**
     * When present, this field contains the sender&#x27;s postal code
     *
     * @return senderPostalCode
     **/
    @ApiModelProperty(value = "When present, this field contains the sender's postal code")
    public String getSenderPostalCode() {
        return senderPostalCode;
    }

    public void setSenderPostalCode(String senderPostalCode) {
        this.senderPostalCode = senderPostalCode;
    }

    public PushfundspostPayload senderFirstName(String senderFirstName) {
        this.senderFirstName = senderFirstName;
        return this;
    }


    /**
     * This field contains sender&#x27;s first name
     *
     * @return senderFirstName
     **/
    @ApiModelProperty(value = "This field contains sender's first name")
    public String getSenderFirstName() {
        return senderFirstName;
    }

    public void setSenderFirstName(String senderFirstName) {
        this.senderFirstName = senderFirstName;
    }

    public PushfundspostPayload senderAccountNumber(String senderAccountNumber) {
        this.senderAccountNumber = senderAccountNumber;
        return this;
    }


    /**
     * If the transaction is a money transfer, pre-paid load, or credit card bill pay, and if the sender intends to fund the transaction with a financial instrument (for example, debit card),  this field is required and must contain the sender&#x27;s account number. If the transaction is a funds disbursement, the field is not required.
     *
     * @return senderAccountNumber
     **/
    @ApiModelProperty(value = "If the transaction is a money transfer, pre-paid load, or credit card bill pay, and if the sender intends to fund the transaction with a financial instrument (for example, debit card),  this field is required and must contain the sender's account number. If the transaction is a funds disbursement, the field is not required.")
    public String getSenderAccountNumber() {
        return senderAccountNumber;
    }

    public void setSenderAccountNumber(String senderAccountNumber) {
        this.senderAccountNumber = senderAccountNumber;
    }

    public PushfundspostPayload feeProgramIndicator(String feeProgramIndicator) {
        this.feeProgramIndicator = feeProgramIndicator;
        return this;
    }


    /**
     * Note: If present, a valid value is required. Spaces or special characters are not allowed.
     *
     * @return feeProgramIndicator
     **/
    @ApiModelProperty(value = "Note: If present, a valid value is required. Spaces or special characters are not allowed.")
    public String getFeeProgramIndicator() {
        return feeProgramIndicator;
    }

    public void setFeeProgramIndicator(String feeProgramIndicator) {
        this.feeProgramIndicator = feeProgramIndicator;
    }

    public PushfundspostPayload senderIdentificationNumberBusiness(String senderIdentificationNumberBusiness) {
        this.senderIdentificationNumberBusiness = senderIdentificationNumberBusiness;
        return this;
    }


    /**
     * This is an alphanumeric value that carries the sender’s identification number issued to the sender by the government or an authorized national entity. This field is to be used if the sender is a business (e.g. Disbursements)
     *
     * @return senderIdentificationNumberBusiness
     **/
    @ApiModelProperty(value = "This is an alphanumeric value that carries the sender’s identification number issued to the sender by the government or an authorized national entity. This field is to be used if the sender is a business (e.g. Disbursements)")
    public String getSenderIdentificationNumberBusiness() {
        return senderIdentificationNumberBusiness;
    }

    public void setSenderIdentificationNumberBusiness(String senderIdentificationNumberBusiness) {
        this.senderIdentificationNumberBusiness = senderIdentificationNumberBusiness;
    }

    public PushfundspostPayload transactionCurrencyCode(String transactionCurrencyCode) {
        this.transactionCurrencyCode = transactionCurrencyCode;
        return this;
    }


    /**
     * Use a 3-character alpha or numeric currency code for currency of the sender. You should (unless prohibited by local law / regulation) use the billingCurrencyCode obtained from the Funds Transfer Attribute Inquiry API under Payment Account Attribute Inquiry. &lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#iso_country_and_currency_codes\&quot;&gt;ISO Codes&lt;/a&gt;
     *
     * @return transactionCurrencyCode
     **/
    @ApiModelProperty(required = true, value = "Use a 3-character alpha or numeric currency code for currency of the sender. You should (unless prohibited by local law / regulation) use the billingCurrencyCode obtained from the Funds Transfer Attribute Inquiry API under Payment Account Attribute Inquiry. <br><br>Refer to <a href=\"/request_response_codes#iso_country_and_currency_codes\">ISO Codes</a> ")
    public String getTransactionCurrencyCode() {
        return transactionCurrencyCode;
    }

    public void setTransactionCurrencyCode(String transactionCurrencyCode) {
        this.transactionCurrencyCode = transactionCurrencyCode;
    }

    public PushfundspostPayload acquiringBin(Integer acquiringBin) {
        this.acquiringBin = acquiringBin;
        return this;
    }


    /**
     * The Bank Identification Number (BIN) under which the Visa Direct solution is registered. This must match the information provided during enrollment.
     *
     * @return acquiringBin
     **/
    @ApiModelProperty(required = true, value = "The Bank Identification Number (BIN) under which the Visa Direct solution is registered. This must match the information provided during enrollment.")
    public Integer getAcquiringBin() {
        return acquiringBin;
    }

    public void setAcquiringBin(Integer acquiringBin) {
        this.acquiringBin = acquiringBin;
    }

    public PushfundspostPayload accountType(String accountType) {
        this.accountType = accountType;
        return this;
    }


    /**
     * This is used to identify the account type of the senderPrimaryAccountNumber in the request. Below are the possible values.&lt;br&gt;&lt;br&gt; 00-Not applicable&lt;br&gt; 10-Saving account&lt;br&gt; 20-Checking account&lt;br&gt; 30-Credit card account&lt;br&gt; 40-Universal account&lt;br&gt;&lt;br&gt;Default is set to \&quot;00\&quot; if not provided.
     *
     * @return accountType
     **/
    @ApiModelProperty(value = "This is used to identify the account type of the senderPrimaryAccountNumber in the request. Below are the possible values.<br><br> 00-Not applicable<br> 10-Saving account<br> 20-Checking account<br> 30-Credit card account<br> 40-Universal account<br><br>Default is set to \"00\" if not provided.")
    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public PushfundspostPayload merchantPseudoAbaNumber(String merchantPseudoAbaNumber) {
        this.merchantPseudoAbaNumber = merchantPseudoAbaNumber;
        return this;
    }


    /**
     * This is a number that uniquely identifies the originator when they sign up to send Push Payment Gateway transactions. On enrollment, an originator will get a single pseudo-value that is assigned by Visa. The other networks will assign their own unique values for the originator.&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt;&lt;br&gt;Supported only in US for domestic transactions involving Push Payments Gateway Service.
     *
     * @return merchantPseudoAbaNumber
     **/
    @ApiModelProperty(value = "This is a number that uniquely identifies the originator when they sign up to send Push Payment Gateway transactions. On enrollment, an originator will get a single pseudo-value that is assigned by Visa. The other networks will assign their own unique values for the originator.<br><br><b>Note:</b><br>Supported only in US for domestic transactions involving Push Payments Gateway Service.")
    public String getMerchantPseudoAbaNumber() {
        return merchantPseudoAbaNumber;
    }

    public void setMerchantPseudoAbaNumber(String merchantPseudoAbaNumber) {
        this.merchantPseudoAbaNumber = merchantPseudoAbaNumber;
    }

    public PushfundspostPayload transactionIdentifier(Long transactionIdentifier) {
        this.transactionIdentifier = transactionIdentifier;
        return this;
    }


    /**
     * The VisaNet transaction identifier. If you have previously sent an AFT, this field must include the VisaNet transaction identifier returned in the AFT response.&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt; provide only if there is a corresponding AFT transaction response.
     *
     * @return transactionIdentifier
     **/
    @ApiModelProperty(value = "The VisaNet transaction identifier. If you have previously sent an AFT, this field must include the VisaNet transaction identifier returned in the AFT response.<br><br><b>Note:</b> provide only if there is a corresponding AFT transaction response.")
    public Long getTransactionIdentifier() {
        return transactionIdentifier;
    }

    public void setTransactionIdentifier(Long transactionIdentifier) {
        this.transactionIdentifier = transactionIdentifier;
    }

    public PushfundspostPayload localTransactionDateTime(String localTransactionDateTime) {
        this.localTransactionDateTime = localTransactionDateTime;
        return this;
    }


    /**
     * Get localTransactionDateTime
     *
     * @return localTransactionDateTime
     **/
    @ApiModelProperty(required = true, value = "")
    public String getLocalTransactionDateTime() {
        return localTransactionDateTime;
    }

    public void setLocalTransactionDateTime(String localTransactionDateTime) {
        this.localTransactionDateTime = localTransactionDateTime;
    }

    public PushfundspostPayload recipientFirstName(String recipientFirstName) {
        this.recipientFirstName = recipientFirstName;
        return this;
    }


    /**
     * When present, this field contains recipient&#x27;s first name
     *
     * @return recipientFirstName
     **/
    @ApiModelProperty(value = "When present, this field contains recipient's first name")
    public String getRecipientFirstName() {
        return recipientFirstName;
    }

    public void setRecipientFirstName(String recipientFirstName) {
        this.recipientFirstName = recipientFirstName;
    }

    public PushfundspostPayload amount(Double amount) {
        this.amount = amount;
        return this;
    }


    /**
     * The transaction amount to be delivered to the recipient.
     *
     * @return amount
     **/
    @ApiModelProperty(required = true, value = "The transaction amount to be delivered to the recipient.")
    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public PushfundspostPayload senderDateOfBirth(String senderDateOfBirth) {
        this.senderDateOfBirth = senderDateOfBirth;
        return this;
    }


    /**
     * The birth date for the sender
     *
     * @return senderDateOfBirth
     **/
    @ApiModelProperty(value = "The birth date for the sender")
    public String getSenderDateOfBirth() {
        return senderDateOfBirth;
    }

    public void setSenderDateOfBirth(String senderDateOfBirth) {
        this.senderDateOfBirth = senderDateOfBirth;
    }

    public PushfundspostPayload recipientMiddleInitial(String recipientMiddleInitial) {
        this.recipientMiddleInitial = recipientMiddleInitial;
        return this;
    }


    /**
     * When present, this field contains recipient&#x27;s middle initial
     *
     * @return recipientMiddleInitial
     **/
    @ApiModelProperty(value = "When present, this field contains recipient's middle initial")
    public String getRecipientMiddleInitial() {
        return recipientMiddleInitial;
    }

    public void setRecipientMiddleInitial(String recipientMiddleInitial) {
        this.recipientMiddleInitial = recipientMiddleInitial;
    }

    public PushfundspostPayload recipientCardExpiryDate(String recipientCardExpiryDate) {
        this.recipientCardExpiryDate = recipientCardExpiryDate;
        return this;
    }


    /**
     * The expiration date for the recipient&#x27;s primary account number in  recipientPrimaryAccountNumber
     *
     * @return recipientCardExpiryDate
     **/
    @ApiModelProperty(value = "The expiration date for the recipient's primary account number in  recipientPrimaryAccountNumber")
    public String getRecipientCardExpiryDate() {
        return recipientCardExpiryDate;
    }

    public void setRecipientCardExpiryDate(String recipientCardExpiryDate) {
        this.recipientCardExpiryDate = recipientCardExpiryDate;
    }

    public PushfundspostPayload recipientCountryCode(String recipientCountryCode) {
        this.recipientCountryCode = recipientCountryCode;
        return this;
    }


    /**
     * when present, this field contains recipient&#x27;s country code &lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#iso_country_codes\&quot;&gt;ISO Codes&lt;/a&gt;
     *
     * @return recipientCountryCode
     **/
    @ApiModelProperty(value = "when present, this field contains recipient's country code <br><br>Refer to <a href=\"/request_response_codes#iso_country_codes\">ISO Codes</a>")
    public String getRecipientCountryCode() {
        return recipientCountryCode;
    }

    public void setRecipientCountryCode(String recipientCountryCode) {
        this.recipientCountryCode = recipientCountryCode;
    }

    public PushfundspostPayload senderIdentificationNumberIndividual(String senderIdentificationNumberIndividual) {
        this.senderIdentificationNumberIndividual = senderIdentificationNumberIndividual;
        return this;
    }


    /**
     * This is an alphanumeric value that carries the sender’s identification number issued to the sender by the government or an authorized national entity. This field is to be used if the sender is an Individual (e.g. P2P payments)
     *
     * @return senderIdentificationNumberIndividual
     **/
    @ApiModelProperty(value = "This is an alphanumeric value that carries the sender’s identification number issued to the sender by the government or an authorized national entity. This field is to be used if the sender is an Individual (e.g. P2P payments)")
    public String getSenderIdentificationNumberIndividual() {
        return senderIdentificationNumberIndividual;
    }

    public void setSenderIdentificationNumberIndividual(String senderIdentificationNumberIndividual) {
        this.senderIdentificationNumberIndividual = senderIdentificationNumberIndividual;
    }

    public PushfundspostPayload systemsTraceAuditNumber(Integer systemsTraceAuditNumber) {
        this.systemsTraceAuditNumber = systemsTraceAuditNumber;
        return this;
    }


    /**
     * A unique value should be used for each API method. However, when passing the (AFTR) method, this value must match the systemsTraceAuditNumber previously passed with the AFT method for the current transaction.
     *
     * @return systemsTraceAuditNumber
     **/
    @ApiModelProperty(required = true, value = "A unique value should be used for each API method. However, when passing the (AFTR) method, this value must match the systemsTraceAuditNumber previously passed with the AFT method for the current transaction.")
    public Integer getSystemsTraceAuditNumber() {
        return systemsTraceAuditNumber;
    }

    public void setSystemsTraceAuditNumber(Integer systemsTraceAuditNumber) {
        this.systemsTraceAuditNumber = systemsTraceAuditNumber;
    }

    public PushfundspostPayload senderCountryCode(String senderCountryCode) {
        this.senderCountryCode = senderCountryCode;
        return this;
    }


    /**
     * If the transaction is a money transfer and cross-border or U.S. domestic, this field must contain the sender&#x27;s country code.&lt;br&gt;&lt;br&gt;If the transaction is a funds disbursement and cross-border or U.S. domestic, this field must contain either the country code of the merchant or government entity sending the funds disbursement.&lt;br&gt;&lt;br&gt;If the transaction is a pre-paid load or credit card bill pay and U.S. domestic, this field must contain the sender&#x27;s country code.&lt;br&gt;&lt;br&gt;Alpha or numeric country code can be supported.&lt;br&gt;&lt;br&gt;This field is required when sending the transactions to some of the US debit networks.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#iso_country_and_currency_codes\&quot;&gt;ISO Codes&lt;/a&gt;
     *
     * @return senderCountryCode
     **/
    @ApiModelProperty(value = "If the transaction is a money transfer and cross-border or U.S. domestic, this field must contain the sender's country code.<br><br>If the transaction is a funds disbursement and cross-border or U.S. domestic, this field must contain either the country code of the merchant or government entity sending the funds disbursement.<br><br>If the transaction is a pre-paid load or credit card bill pay and U.S. domestic, this field must contain the sender's country code.<br><br>Alpha or numeric country code can be supported.<br><br>This field is required when sending the transactions to some of the US debit networks.<br><br>Refer to <a href=\"/request_response_codes#iso_country_and_currency_codes\">ISO Codes</a>")
    public String getSenderCountryCode() {
        return senderCountryCode;
    }

    public void setSenderCountryCode(String senderCountryCode) {
        this.senderCountryCode = senderCountryCode;
    }

    public PushfundspostPayload merchantVerificationValue(MerchantVerificationValue merchantVerificationValue) {
        this.merchantVerificationValue = merchantVerificationValue;
        return this;
    }


    /**
     * Get merchantVerificationValue
     *
     * @return merchantVerificationValue
     **/
    @ApiModelProperty(value = "")
    public MerchantVerificationValue getMerchantVerificationValue() {
        return merchantVerificationValue;
    }

    public void setMerchantVerificationValue(MerchantVerificationValue merchantVerificationValue) {
        this.merchantVerificationValue = merchantVerificationValue;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PushfundspostPayload pushfundspostPayload = (PushfundspostPayload) o;
        return Objects.equals(this.businessApplicationId, pushfundspostPayload.businessApplicationId) &&
                Objects.equals(this.retrievalReferenceNumber, pushfundspostPayload.retrievalReferenceNumber) &&
                Objects.equals(this.cardAcceptor, pushfundspostPayload.cardAcceptor) &&
                Objects.equals(this.messageReasonCode, pushfundspostPayload.messageReasonCode) &&
                Objects.equals(this.senderAddress, pushfundspostPayload.senderAddress) &&
                Objects.equals(this.senderCity, pushfundspostPayload.senderCity) &&
                Objects.equals(this.sourceOfFundsCode, pushfundspostPayload.sourceOfFundsCode) &&
                Objects.equals(this.recipientName, pushfundspostPayload.recipientName) &&
                Objects.equals(this.senderMiddleInitial, pushfundspostPayload.senderMiddleInitial) &&
                Objects.equals(this.senderName, pushfundspostPayload.senderName) &&
                Objects.equals(this.recipientState, pushfundspostPayload.recipientState) &&
                Objects.equals(this.surcharge, pushfundspostPayload.surcharge) &&
                Objects.equals(this.senderStateCode, pushfundspostPayload.senderStateCode) &&
                Objects.equals(this.merchantCategoryCode, pushfundspostPayload.merchantCategoryCode) &&
                Objects.equals(this.senderLastName, pushfundspostPayload.senderLastName) &&
                Objects.equals(this.pointOfServiceData, pushfundspostPayload.pointOfServiceData) &&
                Objects.equals(this.sharingGroupCode, pushfundspostPayload.sharingGroupCode) &&
                Objects.equals(this.acquirerCountryCode, pushfundspostPayload.acquirerCountryCode) &&
                Objects.equals(this.senderReference, pushfundspostPayload.senderReference) &&
                Objects.equals(this.recipientPrimaryAccountNumber, pushfundspostPayload.recipientPrimaryAccountNumber) &&
                Objects.equals(this.recipientLastName, pushfundspostPayload.recipientLastName) &&
                Objects.equals(this.nationalReimbursementFee, pushfundspostPayload.nationalReimbursementFee) &&
                Objects.equals(this.senderPostalCode, pushfundspostPayload.senderPostalCode) &&
                Objects.equals(this.senderFirstName, pushfundspostPayload.senderFirstName) &&
                Objects.equals(this.senderAccountNumber, pushfundspostPayload.senderAccountNumber) &&
                Objects.equals(this.feeProgramIndicator, pushfundspostPayload.feeProgramIndicator) &&
                Objects.equals(this.senderIdentificationNumberBusiness, pushfundspostPayload.senderIdentificationNumberBusiness) &&
                Objects.equals(this.transactionCurrencyCode, pushfundspostPayload.transactionCurrencyCode) &&
                Objects.equals(this.acquiringBin, pushfundspostPayload.acquiringBin) &&
                Objects.equals(this.accountType, pushfundspostPayload.accountType) &&
                Objects.equals(this.merchantPseudoAbaNumber, pushfundspostPayload.merchantPseudoAbaNumber) &&
                Objects.equals(this.transactionIdentifier, pushfundspostPayload.transactionIdentifier) &&
                Objects.equals(this.localTransactionDateTime, pushfundspostPayload.localTransactionDateTime) &&
                Objects.equals(this.recipientFirstName, pushfundspostPayload.recipientFirstName) &&
                Objects.equals(this.amount, pushfundspostPayload.amount) &&
                Objects.equals(this.senderDateOfBirth, pushfundspostPayload.senderDateOfBirth) &&
                Objects.equals(this.recipientMiddleInitial, pushfundspostPayload.recipientMiddleInitial) &&
                Objects.equals(this.recipientCardExpiryDate, pushfundspostPayload.recipientCardExpiryDate) &&
                Objects.equals(this.recipientCountryCode, pushfundspostPayload.recipientCountryCode) &&
                Objects.equals(this.senderIdentificationNumberIndividual, pushfundspostPayload.senderIdentificationNumberIndividual) &&
                Objects.equals(this.systemsTraceAuditNumber, pushfundspostPayload.systemsTraceAuditNumber) &&
                Objects.equals(this.senderCountryCode, pushfundspostPayload.senderCountryCode) &&
                Objects.equals(this.merchantVerificationValue, pushfundspostPayload.merchantVerificationValue);
    }

    @Override
    public int hashCode() {
        return Objects.hash(businessApplicationId, retrievalReferenceNumber, cardAcceptor, messageReasonCode, senderAddress, senderCity, sourceOfFundsCode, recipientName, senderMiddleInitial, senderName, recipientState, surcharge, senderStateCode, merchantCategoryCode, senderLastName, pointOfServiceData, sharingGroupCode, acquirerCountryCode, senderReference, recipientPrimaryAccountNumber, recipientLastName, nationalReimbursementFee, senderPostalCode, senderFirstName, senderAccountNumber, feeProgramIndicator, senderIdentificationNumberBusiness, transactionCurrencyCode, acquiringBin, accountType, merchantPseudoAbaNumber, transactionIdentifier, localTransactionDateTime, recipientFirstName, amount, senderDateOfBirth, recipientMiddleInitial, recipientCardExpiryDate, recipientCountryCode, senderIdentificationNumberIndividual, systemsTraceAuditNumber, senderCountryCode, merchantVerificationValue);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PushfundspostPayload {\n");

        sb.append("    businessApplicationId: ").append(toIndentedString(businessApplicationId)).append("\n");
        sb.append("    retrievalReferenceNumber: ").append(toIndentedString(retrievalReferenceNumber)).append("\n");
        sb.append("    cardAcceptor: ").append(toIndentedString(cardAcceptor)).append("\n");
        sb.append("    messageReasonCode: ").append(toIndentedString(messageReasonCode)).append("\n");
        sb.append("    senderAddress: ").append(toIndentedString(senderAddress)).append("\n");
        sb.append("    senderCity: ").append(toIndentedString(senderCity)).append("\n");
        sb.append("    sourceOfFundsCode: ").append(toIndentedString(sourceOfFundsCode)).append("\n");
        sb.append("    recipientName: ").append(toIndentedString(recipientName)).append("\n");
        sb.append("    senderMiddleInitial: ").append(toIndentedString(senderMiddleInitial)).append("\n");
        sb.append("    senderName: ").append(toIndentedString(senderName)).append("\n");
        sb.append("    recipientState: ").append(toIndentedString(recipientState)).append("\n");
        sb.append("    surcharge: ").append(toIndentedString(surcharge)).append("\n");
        sb.append("    senderStateCode: ").append(toIndentedString(senderStateCode)).append("\n");
        sb.append("    merchantCategoryCode: ").append(toIndentedString(merchantCategoryCode)).append("\n");
        sb.append("    senderLastName: ").append(toIndentedString(senderLastName)).append("\n");
        sb.append("    pointOfServiceData: ").append(toIndentedString(pointOfServiceData)).append("\n");
        sb.append("    sharingGroupCode: ").append(toIndentedString(sharingGroupCode)).append("\n");
        sb.append("    acquirerCountryCode: ").append(toIndentedString(acquirerCountryCode)).append("\n");
        sb.append("    senderReference: ").append(toIndentedString(senderReference)).append("\n");
        sb.append("    recipientPrimaryAccountNumber: ").append(toIndentedString(recipientPrimaryAccountNumber)).append("\n");
        sb.append("    recipientLastName: ").append(toIndentedString(recipientLastName)).append("\n");
        sb.append("    nationalReimbursementFee: ").append(toIndentedString(nationalReimbursementFee)).append("\n");
        sb.append("    senderPostalCode: ").append(toIndentedString(senderPostalCode)).append("\n");
        sb.append("    senderFirstName: ").append(toIndentedString(senderFirstName)).append("\n");
        sb.append("    senderAccountNumber: ").append(toIndentedString(senderAccountNumber)).append("\n");
        sb.append("    feeProgramIndicator: ").append(toIndentedString(feeProgramIndicator)).append("\n");
        sb.append("    senderIdentificationNumberBusiness: ").append(toIndentedString(senderIdentificationNumberBusiness)).append("\n");
        sb.append("    transactionCurrencyCode: ").append(toIndentedString(transactionCurrencyCode)).append("\n");
        sb.append("    acquiringBin: ").append(toIndentedString(acquiringBin)).append("\n");
        sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
        sb.append("    merchantPseudoAbaNumber: ").append(toIndentedString(merchantPseudoAbaNumber)).append("\n");
        sb.append("    transactionIdentifier: ").append(toIndentedString(transactionIdentifier)).append("\n");
        sb.append("    localTransactionDateTime: ").append(toIndentedString(localTransactionDateTime)).append("\n");
        sb.append("    recipientFirstName: ").append(toIndentedString(recipientFirstName)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    senderDateOfBirth: ").append(toIndentedString(senderDateOfBirth)).append("\n");
        sb.append("    recipientMiddleInitial: ").append(toIndentedString(recipientMiddleInitial)).append("\n");
        sb.append("    recipientCardExpiryDate: ").append(toIndentedString(recipientCardExpiryDate)).append("\n");
        sb.append("    recipientCountryCode: ").append(toIndentedString(recipientCountryCode)).append("\n");
        sb.append("    senderIdentificationNumberIndividual: ").append(toIndentedString(senderIdentificationNumberIndividual)).append("\n");
        sb.append("    systemsTraceAuditNumber: ").append(toIndentedString(systemsTraceAuditNumber)).append("\n");
        sb.append("    senderCountryCode: ").append(toIndentedString(senderCountryCode)).append("\n");
        sb.append("    merchantVerificationValue: ").append(toIndentedString(merchantVerificationValue)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}



