/*
 * *© Copyright 2018 - 2020 Visa. All Rights Reserved.**
 *
 * NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.*
 *
 *  By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy (developer.visa.com/privacy).In addition, all permissible uses of the Software must be in support of Visa products, programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com). **THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL FAULTS” BASIS WITHOUT WARRANTY OR  CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.** All brand names are the property of their respective owners, used for identification purposes only, and do not imply product endorsement or affiliation with Visa. Any links to third party sites are for your information only and equally  do not constitute a Visa endorsement. Visa has no insight into and control over third party content and code and disclaims all liability for any such components, including continued availability and functionality. Benefits depend on implementation details and business factors and coding steps shown are exemplary only and do not reflect all necessary elements for the described capabilities. Capabilities and features are subject to Visa’s terms and conditions and may require development,implementation and resources by you based on your business and operational details. Please refer to the specific API documentation for details on the requirements, eligibility and geographic availability.*
 *
 * This Software includes programs, concepts and details under continuing development by Visa. Any Visa features,functionality, implementation, branding, and schedules may be amended, updated or canceled at Visa’s discretion.The timing of widespread availability of programs and functionality is also subject to a number of factors outside Visa’s control,including but not limited to deployment of necessary infrastructure by issuers, acquirers, merchants and mobile device manufacturers.*
 *
 */

/*
 * Funds Transfer API
 * The Funds Transfer API can pull funds from the sender&apos;s Visa account (in preparation for pushing funds to a recipient&apos;s account) in an Account Funding Transaction (AFT).  Additionally, the Funds Transfer API also provides functionality to push funds to the recipient&apos;s Visa account in an Original Credit Transaction (OCT).  If a transaction is declined, the Funds Transfer API can also return the funds to the sender&apos;s funding source in an Account Funding Transaction Reversal (AFTR). The API has been enhanced to allow originators to send their PushFundsTransactions(OCTs) and PullFundsTransactions(AFTs) to Visa for routing to multiple U.S. debit networks.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.visa.developer.sample.funds_transfer_api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Request body for creating in reverse funds transfer
 */
@ApiModel(description = "Request body for creating in reverse funds transfer")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2019-03-27T10:55:08.119+05:30[Asia/Kolkata]")
public class ReversefundspostPayload {


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("businessApplicationId")
    private String businessApplicationId = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("transactionIdentifier")
    private Long transactionIdentifier = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("cardAcceptor")
    private CardAcceptor cardAcceptor = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("surcharge")
    private String surcharge = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("networkId")
    private Integer networkId = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("merchantCategoryCode")
    private Integer merchantCategoryCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("merchantVerificationValue")
    private MerchantVerificationValue merchantVerificationValue = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("sharingGroupCode")
    private String sharingGroupCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("acquirerCountryCode")
    private Integer acquirerCountryCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("systemsTraceAuditNumber")
    private Integer systemsTraceAuditNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("originalDataElements")
    private OriginalDataElements originalDataElements = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("memberComments")
    private String memberComments = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("nationalReimbursementFee")
    private Double nationalReimbursementFee = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("feeProgramIndicator")
    private String feeProgramIndicator = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("retrievalReferenceNumber")
    private String retrievalReferenceNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("acquiringBin")
    private Integer acquiringBin = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("accountType")
    private String accountType = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("merchantPseudoAbaNumber")
    private String merchantPseudoAbaNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("foreignExchangeFeeTransaction")
    private Double foreignExchangeFeeTransaction = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("pointOfServiceData")
    private PointOfServiceData pointOfServiceData = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderPrimaryAccountNumber")
    private String senderPrimaryAccountNumber = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("localTransactionDateTime")
    private String localTransactionDateTime = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderCardExpiryDate")
    private String senderCardExpiryDate = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("amount")
    private Double amount = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("senderCurrencyCode")
    private String senderCurrencyCode = null;


    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @JsonProperty("pointOfServiceCapability")
    private PointOfServiceCapability pointOfServiceCapability = null;

    public ReversefundspostPayload businessApplicationId(String businessApplicationId) {
        this.businessApplicationId = businessApplicationId;
        return this;
    }


    /**
     * Identifies the programs&#x27; business application type for VisaNet transaction processing&lt;br&gt;&lt;br&gt;For Money Transfer, AA applies to transactions where the sender and recipient are the same person and PP applies to transactions where the sender and recipient are not the same person.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#business_application_identifier\&quot;&gt;businessApplicationId&lt;/a&gt; codes
     *
     * @return businessApplicationId
     **/
    @ApiModelProperty(required = true, value = "Identifies the programs' business application type for VisaNet transaction processing<br><br>For Money Transfer, AA applies to transactions where the sender and recipient are the same person and PP applies to transactions where the sender and recipient are not the same person.<br><br>Refer to <a href=\"/request_response_codes#business_application_identifier\">businessApplicationId</a> codes")
    public String getBusinessApplicationId() {
        return businessApplicationId;
    }

    public void setBusinessApplicationId(String businessApplicationId) {
        this.businessApplicationId = businessApplicationId;
    }

    public ReversefundspostPayload transactionIdentifier(Long transactionIdentifier) {
        this.transactionIdentifier = transactionIdentifier;
        return this;
    }


    /**
     * The VisaNet reference number for the transaction. You must use the transactionIdentifier from the initial AFT in this field.
     *
     * @return transactionIdentifier
     **/
    @ApiModelProperty(required = true, value = "The VisaNet reference number for the transaction. You must use the transactionIdentifier from the initial AFT in this field.")
    public Long getTransactionIdentifier() {
        return transactionIdentifier;
    }

    public void setTransactionIdentifier(Long transactionIdentifier) {
        this.transactionIdentifier = transactionIdentifier;
    }

    public ReversefundspostPayload cardAcceptor(CardAcceptor cardAcceptor) {
        this.cardAcceptor = cardAcceptor;
        return this;
    }


    /**
     * Get cardAcceptor
     *
     * @return cardAcceptor
     **/
    @ApiModelProperty(required = true, value = "")
    public CardAcceptor getCardAcceptor() {
        return cardAcceptor;
    }

    public void setCardAcceptor(CardAcceptor cardAcceptor) {
        this.cardAcceptor = cardAcceptor;
    }

    public ReversefundspostPayload surcharge(String surcharge) {
        this.surcharge = surcharge;
        return this;
    }


    /**
     * When present, this field contains the sender&#x27;s surcharge as assessed by the originator. Values in this field must be in the same currency and format as defined in the amount field.
     *
     * @return surcharge
     **/
    @ApiModelProperty(value = "When present, this field contains the sender's surcharge as assessed by the originator. Values in this field must be in the same currency and format as defined in the amount field.")
    public String getSurcharge() {
        return surcharge;
    }

    public void setSurcharge(String surcharge) {
        this.surcharge = surcharge;
    }

    public ReversefundspostPayload networkId(Integer networkId) {
        this.networkId = networkId;
        return this;
    }


    /**
     * This contains a code that specifies the network to be used for transmission of the message and determines the program rules that apply to the transaction.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#network_id_and_sharing_group_code\&quot;&gt;Network ID&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt;&lt;br&gt;For ReverseFundsTransactions(AFTR) and MultiReverseFundsTransactions (MULTIAFTR) originators must populate the networkId returned in the original PullFundsTransactions(AFT) and  MultiPullFundsTransactions (MULTIAFT) response.&lt;br&gt; Supported only in US for domestic transactions.
     *
     * @return networkId
     **/
    @ApiModelProperty(value = "This contains a code that specifies the network to be used for transmission of the message and determines the program rules that apply to the transaction.<br><br>Refer to <a href=\"/request_response_codes#network_id_and_sharing_group_code\">Network ID</a><br><br><b>Note:</b><br>For ReverseFundsTransactions(AFTR) and MultiReverseFundsTransactions (MULTIAFTR) originators must populate the networkId returned in the original PullFundsTransactions(AFT) and  MultiPullFundsTransactions (MULTIAFT) response.<br> Supported only in US for domestic transactions.")
    public Integer getNetworkId() {
        return networkId;
    }

    public void setNetworkId(Integer networkId) {
        this.networkId = networkId;
    }

    public ReversefundspostPayload merchantCategoryCode(Integer merchantCategoryCode) {
        this.merchantCategoryCode = merchantCategoryCode;
        return this;
    }


    /**
     * If provided, then the value overrides the one present in onboarding data. If the merchantCategoryCode value is not populated in onboarding data then this field is mandatory.&lt;br&gt;&lt;br&gt;If not provided, then the value will default to the values provided during onboarding (when the services are provisioned)&lt;b&gt;Note:&lt;/b&gt; required if not provided during onboarding
     *
     * @return merchantCategoryCode
     **/
    @ApiModelProperty(required = true, value = "If provided, then the value overrides the one present in onboarding data. If the merchantCategoryCode value is not populated in onboarding data then this field is mandatory.<br><br>If not provided, then the value will default to the values provided during onboarding (when the services are provisioned)<b>Note:</b> required if not provided during onboarding")
    public Integer getMerchantCategoryCode() {
        return merchantCategoryCode;
    }

    public void setMerchantCategoryCode(Integer merchantCategoryCode) {
        this.merchantCategoryCode = merchantCategoryCode;
    }

    public ReversefundspostPayload merchantVerificationValue(MerchantVerificationValue merchantVerificationValue) {
        this.merchantVerificationValue = merchantVerificationValue;
        return this;
    }


    /**
     * Get merchantVerificationValue
     *
     * @return merchantVerificationValue
     **/
    @ApiModelProperty(value = "")
    public MerchantVerificationValue getMerchantVerificationValue() {
        return merchantVerificationValue;
    }

    public void setMerchantVerificationValue(MerchantVerificationValue merchantVerificationValue) {
        this.merchantVerificationValue = merchantVerificationValue;
    }

    public ReversefundspostPayload sharingGroupCode(String sharingGroupCode) {
        this.sharingGroupCode = sharingGroupCode;
        return this;
    }


    /**
     * This field is optionally used by Push Payments Gateway participants (merchants and acquirers) to specify the network access priority.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#network_id_and_sharing_group_code\&quot;&gt;Sharing Group Code&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt;&lt;br&gt;Supported only in US for domestic transactions involving Push Payments Gateway Service.
     *
     * @return sharingGroupCode
     **/
    @ApiModelProperty(value = "This field is optionally used by Push Payments Gateway participants (merchants and acquirers) to specify the network access priority.<br><br>Refer to <a href=\"/request_response_codes#network_id_and_sharing_group_code\">Sharing Group Code</a><br><br><b>Note:</b><br>Supported only in US for domestic transactions involving Push Payments Gateway Service.")
    public String getSharingGroupCode() {
        return sharingGroupCode;
    }

    public void setSharingGroupCode(String sharingGroupCode) {
        this.sharingGroupCode = sharingGroupCode;
    }

    public ReversefundspostPayload acquirerCountryCode(Integer acquirerCountryCode) {
        this.acquirerCountryCode = acquirerCountryCode;
        return this;
    }


    /**
     * Use a 3-digit numeric country code for the country of the BIN under which your Visa Direct solution is registered. This must match the information provided during program enrollment.
     *
     * @return acquirerCountryCode
     **/
    @ApiModelProperty(required = true, value = "Use a 3-digit numeric country code for the country of the BIN under which your Visa Direct solution is registered. This must match the information provided during program enrollment.")
    public Integer getAcquirerCountryCode() {
        return acquirerCountryCode;
    }

    public void setAcquirerCountryCode(Integer acquirerCountryCode) {
        this.acquirerCountryCode = acquirerCountryCode;
    }

    public ReversefundspostPayload systemsTraceAuditNumber(Integer systemsTraceAuditNumber) {
        this.systemsTraceAuditNumber = systemsTraceAuditNumber;
        return this;
    }


    /**
     * A unique value should be used for each API method. however, when passing the Account Funding Transaction Reversal (AFTR) method, this value must match the systemsTraceAuditNumber previously passed with the AFT method for the current transaction.
     *
     * @return systemsTraceAuditNumber
     **/
    @ApiModelProperty(required = true, value = "A unique value should be used for each API method. however, when passing the Account Funding Transaction Reversal (AFTR) method, this value must match the systemsTraceAuditNumber previously passed with the AFT method for the current transaction.")
    public Integer getSystemsTraceAuditNumber() {
        return systemsTraceAuditNumber;
    }

    public void setSystemsTraceAuditNumber(Integer systemsTraceAuditNumber) {
        this.systemsTraceAuditNumber = systemsTraceAuditNumber;
    }

    public ReversefundspostPayload originalDataElements(OriginalDataElements originalDataElements) {
        this.originalDataElements = originalDataElements;
        return this;
    }


    /**
     * Get originalDataElements
     *
     * @return originalDataElements
     **/
    @ApiModelProperty(required = true, value = "")
    public OriginalDataElements getOriginalDataElements() {
        return originalDataElements;
    }

    public void setOriginalDataElements(OriginalDataElements originalDataElements) {
        this.originalDataElements = originalDataElements;
    }

    public ReversefundspostPayload memberComments(String memberComments) {
        this.memberComments = memberComments;
        return this;
    }


    /**
     * This field can be optionally used to send and receive comments by service providers. Issuers can optionally include new text in this field in the response. If the issuer does not include this field, Visa will inject the value from the request in the response and send it back to the service provider.
     *
     * @return memberComments
     **/
    @ApiModelProperty(value = "This field can be optionally used to send and receive comments by service providers. Issuers can optionally include new text in this field in the response. If the issuer does not include this field, Visa will inject the value from the request in the response and send it back to the service provider.")
    public String getMemberComments() {
        return memberComments;
    }

    public void setMemberComments(String memberComments) {
        this.memberComments = memberComments;
    }

    public ReversefundspostPayload nationalReimbursementFee(Double nationalReimbursementFee) {
        this.nationalReimbursementFee = nationalReimbursementFee;
        return this;
    }


    /**
     * When present, this field contains the IRF fees.
     *
     * @return nationalReimbursementFee
     **/
    @ApiModelProperty(value = "When present, this field contains the IRF fees.")
    public Double getNationalReimbursementFee() {
        return nationalReimbursementFee;
    }

    public void setNationalReimbursementFee(Double nationalReimbursementFee) {
        this.nationalReimbursementFee = nationalReimbursementFee;
    }

    public ReversefundspostPayload feeProgramIndicator(String feeProgramIndicator) {
        this.feeProgramIndicator = feeProgramIndicator;
        return this;
    }


    /**
     * If present, a valid value is required. Spaces or special characters are not allowed.
     *
     * @return feeProgramIndicator
     **/
    @ApiModelProperty(value = "If present, a valid value is required. Spaces or special characters are not allowed.")
    public String getFeeProgramIndicator() {
        return feeProgramIndicator;
    }

    public void setFeeProgramIndicator(String feeProgramIndicator) {
        this.feeProgramIndicator = feeProgramIndicator;
    }

    public ReversefundspostPayload retrievalReferenceNumber(String retrievalReferenceNumber) {
        this.retrievalReferenceNumber = retrievalReferenceNumber;
        return this;
    }


    /**
     * A value used to tie together service calls related to a single financial transaction. When passing Account Funding Transaction (AFT) and Original Credit Transaction (OCT) methods, this value must differ between the two methods. When passing the Account Funding Transaction Reversal (AFTR) method, this value must match the retrievalReferenceNumber previously passed with the AFT method for this transaction.&lt;br&gt;&lt;br&gt;Recommended Format: ydddhhnnnnnn&lt;br&gt;&lt;br&gt;The first fours digits must be a valid yddd date in the Julian date format, where the first digit &#x3D; 0-9 (last digit of current year) and the next three digits &#x3D; 001-366 (number of the day in the year).&lt;br&gt;&lt;br&gt;hh can be the two digit hour in a 24 hour clock (00-23) during which the transaction is performed.&lt;br&gt;&lt;br&gt;nnnnnn can be the systemsTraceAuditNumber or any 6 digit number.
     *
     * @return retrievalReferenceNumber
     **/
    @ApiModelProperty(required = true, value = "A value used to tie together service calls related to a single financial transaction. When passing Account Funding Transaction (AFT) and Original Credit Transaction (OCT) methods, this value must differ between the two methods. When passing the Account Funding Transaction Reversal (AFTR) method, this value must match the retrievalReferenceNumber previously passed with the AFT method for this transaction.<br><br>Recommended Format: ydddhhnnnnnn<br><br>The first fours digits must be a valid yddd date in the Julian date format, where the first digit = 0-9 (last digit of current year) and the next three digits = 001-366 (number of the day in the year).<br><br>hh can be the two digit hour in a 24 hour clock (00-23) during which the transaction is performed.<br><br>nnnnnn can be the systemsTraceAuditNumber or any 6 digit number.")
    public String getRetrievalReferenceNumber() {
        return retrievalReferenceNumber;
    }

    public void setRetrievalReferenceNumber(String retrievalReferenceNumber) {
        this.retrievalReferenceNumber = retrievalReferenceNumber;
    }

    public ReversefundspostPayload acquiringBin(Integer acquiringBin) {
        this.acquiringBin = acquiringBin;
        return this;
    }


    /**
     * The Bank Identification Number (BIN) under which your Visa Direct is registered. This must match the information provided during enrollment.
     *
     * @return acquiringBin
     **/
    @ApiModelProperty(required = true, value = "The Bank Identification Number (BIN) under which your Visa Direct is registered. This must match the information provided during enrollment.")
    public Integer getAcquiringBin() {
        return acquiringBin;
    }

    public void setAcquiringBin(Integer acquiringBin) {
        this.acquiringBin = acquiringBin;
    }

    public ReversefundspostPayload accountType(String accountType) {
        this.accountType = accountType;
        return this;
    }


    /**
     * This is used to identify the account type of the senderPrimaryAccountNumber in the request. Below are the possible values.&lt;br&gt;&lt;br&gt; 00-Not applicable&lt;br&gt; 10-Saving account&lt;br&gt; 20-Checking account&lt;br&gt; 30-Credit card account&lt;br&gt; 40-Universal account&lt;br&gt;&lt;br&gt;Default is set to \&quot;00\&quot; if not provided.
     *
     * @return accountType
     **/
    @ApiModelProperty(value = "This is used to identify the account type of the senderPrimaryAccountNumber in the request. Below are the possible values.<br><br> 00-Not applicable<br> 10-Saving account<br> 20-Checking account<br> 30-Credit card account<br> 40-Universal account<br><br>Default is set to \"00\" if not provided.")
    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public ReversefundspostPayload merchantPseudoAbaNumber(String merchantPseudoAbaNumber) {
        this.merchantPseudoAbaNumber = merchantPseudoAbaNumber;
        return this;
    }


    /**
     * This is a number that uniquely identifies the originator when they sign up to send Push Payment Gateway transactions. On enrollment, an originator will get a single pseudo-value that is assigned by Visa. The other networks will assign their own unique values for the originator.&lt;br&gt;&lt;br&gt;&lt;b&gt;Note:&lt;/b&gt;&lt;br&gt;Supported only in US for domestic transactions involving Push Payments Gateway Service.
     *
     * @return merchantPseudoAbaNumber
     **/
    @ApiModelProperty(value = "This is a number that uniquely identifies the originator when they sign up to send Push Payment Gateway transactions. On enrollment, an originator will get a single pseudo-value that is assigned by Visa. The other networks will assign their own unique values for the originator.<br><br><b>Note:</b><br>Supported only in US for domestic transactions involving Push Payments Gateway Service.")
    public String getMerchantPseudoAbaNumber() {
        return merchantPseudoAbaNumber;
    }

    public void setMerchantPseudoAbaNumber(String merchantPseudoAbaNumber) {
        this.merchantPseudoAbaNumber = merchantPseudoAbaNumber;
    }

    public ReversefundspostPayload foreignExchangeFeeTransaction(Double foreignExchangeFeeTransaction) {
        this.foreignExchangeFeeTransaction = foreignExchangeFeeTransaction;
        return this;
    }


    /**
     * When present, this field contains the sender&#x27;s foreign exchange markup fee (markup above the wholesale or VisaNet exchange rate as assessed by the originator.Values in this field must be in the same currency and format as defined in the amount field(minimum value is 0).
     *
     * @return foreignExchangeFeeTransaction
     **/
    @ApiModelProperty(value = "When present, this field contains the sender's foreign exchange markup fee (markup above the wholesale or VisaNet exchange rate as assessed by the originator.Values in this field must be in the same currency and format as defined in the amount field(minimum value is 0).")
    public Double getForeignExchangeFeeTransaction() {
        return foreignExchangeFeeTransaction;
    }

    public void setForeignExchangeFeeTransaction(Double foreignExchangeFeeTransaction) {
        this.foreignExchangeFeeTransaction = foreignExchangeFeeTransaction;
    }

    public ReversefundspostPayload pointOfServiceData(PointOfServiceData pointOfServiceData) {
        this.pointOfServiceData = pointOfServiceData;
        return this;
    }


    /**
     * Get pointOfServiceData
     *
     * @return pointOfServiceData
     **/
    @ApiModelProperty(value = "")
    public PointOfServiceData getPointOfServiceData() {
        return pointOfServiceData;
    }

    public void setPointOfServiceData(PointOfServiceData pointOfServiceData) {
        this.pointOfServiceData = pointOfServiceData;
    }

    public ReversefundspostPayload senderPrimaryAccountNumber(String senderPrimaryAccountNumber) {
        this.senderPrimaryAccountNumber = senderPrimaryAccountNumber;
        return this;
    }


    /**
     * The primary account number of the sender&#x27;s account.
     *
     * @return senderPrimaryAccountNumber
     **/
    @ApiModelProperty(required = true, value = "The primary account number of the sender's account.")
    public String getSenderPrimaryAccountNumber() {
        return senderPrimaryAccountNumber;
    }

    public void setSenderPrimaryAccountNumber(String senderPrimaryAccountNumber) {
        this.senderPrimaryAccountNumber = senderPrimaryAccountNumber;
    }

    public ReversefundspostPayload localTransactionDateTime(String localTransactionDateTime) {
        this.localTransactionDateTime = localTransactionDateTime;
        return this;
    }


    /**
     * Get localTransactionDateTime
     *
     * @return localTransactionDateTime
     **/
    @ApiModelProperty(required = true, value = "")
    public String getLocalTransactionDateTime() {
        return localTransactionDateTime;
    }

    public void setLocalTransactionDateTime(String localTransactionDateTime) {
        this.localTransactionDateTime = localTransactionDateTime;
    }

    public ReversefundspostPayload senderCardExpiryDate(String senderCardExpiryDate) {
        this.senderCardExpiryDate = senderCardExpiryDate;
        return this;
    }


    /**
     * The expiration date for the sender&#x27;s Visa account number in senderPrimaryAccountNumber.
     *
     * @return senderCardExpiryDate
     **/
    @ApiModelProperty(value = "The expiration date for the sender's Visa account number in senderPrimaryAccountNumber.")
    public String getSenderCardExpiryDate() {
        return senderCardExpiryDate;
    }

    public void setSenderCardExpiryDate(String senderCardExpiryDate) {
        this.senderCardExpiryDate = senderCardExpiryDate;
    }

    public ReversefundspostPayload amount(Double amount) {
        this.amount = amount;
        return this;
    }


    /**
     * The total amount to be sent to the recipient.
     *
     * @return amount
     **/
    @ApiModelProperty(required = true, value = "The total amount to be sent to the recipient.")
    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public ReversefundspostPayload senderCurrencyCode(String senderCurrencyCode) {
        this.senderCurrencyCode = senderCurrencyCode;
        return this;
    }


    /**
     * Use a 3-character alpha or numeric currency code for currency of the sender.&lt;br&gt;&lt;br&gt;Refer to &lt;a href&#x3D;\&quot;/request_response_codes#iso_country_and_currency_codes\&quot;&gt;ISO Codes&lt;/a&gt;
     *
     * @return senderCurrencyCode
     **/
    @ApiModelProperty(required = true, value = "Use a 3-character alpha or numeric currency code for currency of the sender.<br><br>Refer to <a href=\"/request_response_codes#iso_country_and_currency_codes\">ISO Codes</a>")
    public String getSenderCurrencyCode() {
        return senderCurrencyCode;
    }

    public void setSenderCurrencyCode(String senderCurrencyCode) {
        this.senderCurrencyCode = senderCurrencyCode;
    }

    public ReversefundspostPayload pointOfServiceCapability(PointOfServiceCapability pointOfServiceCapability) {
        this.pointOfServiceCapability = pointOfServiceCapability;
        return this;
    }


    /**
     * Get pointOfServiceCapability
     *
     * @return pointOfServiceCapability
     **/
    @ApiModelProperty(value = "")
    public PointOfServiceCapability getPointOfServiceCapability() {
        return pointOfServiceCapability;
    }

    public void setPointOfServiceCapability(PointOfServiceCapability pointOfServiceCapability) {
        this.pointOfServiceCapability = pointOfServiceCapability;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReversefundspostPayload reversefundspostPayload = (ReversefundspostPayload) o;
        return Objects.equals(this.businessApplicationId, reversefundspostPayload.businessApplicationId) &&
                Objects.equals(this.transactionIdentifier, reversefundspostPayload.transactionIdentifier) &&
                Objects.equals(this.cardAcceptor, reversefundspostPayload.cardAcceptor) &&
                Objects.equals(this.surcharge, reversefundspostPayload.surcharge) &&
                Objects.equals(this.networkId, reversefundspostPayload.networkId) &&
                Objects.equals(this.merchantCategoryCode, reversefundspostPayload.merchantCategoryCode) &&
                Objects.equals(this.merchantVerificationValue, reversefundspostPayload.merchantVerificationValue) &&
                Objects.equals(this.sharingGroupCode, reversefundspostPayload.sharingGroupCode) &&
                Objects.equals(this.acquirerCountryCode, reversefundspostPayload.acquirerCountryCode) &&
                Objects.equals(this.systemsTraceAuditNumber, reversefundspostPayload.systemsTraceAuditNumber) &&
                Objects.equals(this.originalDataElements, reversefundspostPayload.originalDataElements) &&
                Objects.equals(this.memberComments, reversefundspostPayload.memberComments) &&
                Objects.equals(this.nationalReimbursementFee, reversefundspostPayload.nationalReimbursementFee) &&
                Objects.equals(this.feeProgramIndicator, reversefundspostPayload.feeProgramIndicator) &&
                Objects.equals(this.retrievalReferenceNumber, reversefundspostPayload.retrievalReferenceNumber) &&
                Objects.equals(this.acquiringBin, reversefundspostPayload.acquiringBin) &&
                Objects.equals(this.accountType, reversefundspostPayload.accountType) &&
                Objects.equals(this.merchantPseudoAbaNumber, reversefundspostPayload.merchantPseudoAbaNumber) &&
                Objects.equals(this.foreignExchangeFeeTransaction, reversefundspostPayload.foreignExchangeFeeTransaction) &&
                Objects.equals(this.pointOfServiceData, reversefundspostPayload.pointOfServiceData) &&
                Objects.equals(this.senderPrimaryAccountNumber, reversefundspostPayload.senderPrimaryAccountNumber) &&
                Objects.equals(this.localTransactionDateTime, reversefundspostPayload.localTransactionDateTime) &&
                Objects.equals(this.senderCardExpiryDate, reversefundspostPayload.senderCardExpiryDate) &&
                Objects.equals(this.amount, reversefundspostPayload.amount) &&
                Objects.equals(this.senderCurrencyCode, reversefundspostPayload.senderCurrencyCode) &&
                Objects.equals(this.pointOfServiceCapability, reversefundspostPayload.pointOfServiceCapability);
    }

    @Override
    public int hashCode() {
        return Objects.hash(businessApplicationId, transactionIdentifier, cardAcceptor, surcharge, networkId, merchantCategoryCode, merchantVerificationValue, sharingGroupCode, acquirerCountryCode, systemsTraceAuditNumber, originalDataElements, memberComments, nationalReimbursementFee, feeProgramIndicator, retrievalReferenceNumber, acquiringBin, accountType, merchantPseudoAbaNumber, foreignExchangeFeeTransaction, pointOfServiceData, senderPrimaryAccountNumber, localTransactionDateTime, senderCardExpiryDate, amount, senderCurrencyCode, pointOfServiceCapability);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ReversefundspostPayload {\n");

        sb.append("    businessApplicationId: ").append(toIndentedString(businessApplicationId)).append("\n");
        sb.append("    transactionIdentifier: ").append(toIndentedString(transactionIdentifier)).append("\n");
        sb.append("    cardAcceptor: ").append(toIndentedString(cardAcceptor)).append("\n");
        sb.append("    surcharge: ").append(toIndentedString(surcharge)).append("\n");
        sb.append("    networkId: ").append(toIndentedString(networkId)).append("\n");
        sb.append("    merchantCategoryCode: ").append(toIndentedString(merchantCategoryCode)).append("\n");
        sb.append("    merchantVerificationValue: ").append(toIndentedString(merchantVerificationValue)).append("\n");
        sb.append("    sharingGroupCode: ").append(toIndentedString(sharingGroupCode)).append("\n");
        sb.append("    acquirerCountryCode: ").append(toIndentedString(acquirerCountryCode)).append("\n");
        sb.append("    systemsTraceAuditNumber: ").append(toIndentedString(systemsTraceAuditNumber)).append("\n");
        sb.append("    originalDataElements: ").append(toIndentedString(originalDataElements)).append("\n");
        sb.append("    memberComments: ").append(toIndentedString(memberComments)).append("\n");
        sb.append("    nationalReimbursementFee: ").append(toIndentedString(nationalReimbursementFee)).append("\n");
        sb.append("    feeProgramIndicator: ").append(toIndentedString(feeProgramIndicator)).append("\n");
        sb.append("    retrievalReferenceNumber: ").append(toIndentedString(retrievalReferenceNumber)).append("\n");
        sb.append("    acquiringBin: ").append(toIndentedString(acquiringBin)).append("\n");
        sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
        sb.append("    merchantPseudoAbaNumber: ").append(toIndentedString(merchantPseudoAbaNumber)).append("\n");
        sb.append("    foreignExchangeFeeTransaction: ").append(toIndentedString(foreignExchangeFeeTransaction)).append("\n");
        sb.append("    pointOfServiceData: ").append(toIndentedString(pointOfServiceData)).append("\n");
        sb.append("    senderPrimaryAccountNumber: ").append(toIndentedString(senderPrimaryAccountNumber)).append("\n");
        sb.append("    localTransactionDateTime: ").append(toIndentedString(localTransactionDateTime)).append("\n");
        sb.append("    senderCardExpiryDate: ").append(toIndentedString(senderCardExpiryDate)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    senderCurrencyCode: ").append(toIndentedString(senderCurrencyCode)).append("\n");
        sb.append("    pointOfServiceCapability: ").append(toIndentedString(pointOfServiceCapability)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


}



